export const FILTER = "FILTER";
export const ORDER = "ORDER";
export const RESET = "RESET";
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const NEXT_PAGE = "NEXT_PAGE";
export const PREV_PAGE = "PREV_PAGE";
export const ADD_LOCATION = "ADD_LOCATION";
export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL";
export const HANDLE_NUMBER = "HANDLE_NUMBER";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const CLEAR_COUNTRY = "CLEAR_COUNTRY";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const UPDATE_COUNTRY_DISPLAY ="UPDATE_COUNTRY_DISPLAY";
export const ALPHABETIC_ORDER = "ALPHABETIC_ORDER";
export const POPULATION_ORDER = "POPULATION_ORDER";
export const ACTIVITY_ORDER = "ACTIVITY_ORDER";
export const CONTINENT_ORDER = "CONTINENT_ORDER";
export const FAILURE = "FAILURE";
export const RESET_PAGE = 'RESET_PAGE';
export const SET_FILTER_STATE_ALPHA = 'SET_FILTER_STATE_ALPHA';
export const SET_FILTER_STATE_POPU = 'SET_FILTER_STATE_POPU';
export const SET_FILTER_STATE_CONTINENT = 'SET_FILTER_STATE_CONTINENT';
export const SET_FILTER_STATE_ACTI = 'SET_FILTER_STATE_ACTI';
export const APPLY_FILTERS = 'APPLY_FILTERS';



